//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace The_Intellect_Test
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ITestEntities : DbContext
    {
        public ITestEntities()
            : base("name=ITestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Access_Rights> Access_Rights { get; set; }
        public virtual DbSet<Accounts> Accounts { get; set; }
        public virtual DbSet<Ava> Ava { get; set; }
        public virtual DbSet<FAQ> FAQ { get; set; }
        public virtual DbSet<My_Dictionary> My_Dictionary { get; set; }
        public virtual DbSet<Section> Section { get; set; }
        public virtual DbSet<Themes> Themes { get; set; }
        public virtual DbSet<Words> Words { get; set; }
    }
}
