//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace The_Intellect_Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class My_Dictionary
    {
        public int Id { get; set; }
        public int Id_word { get; set; }
        public int Id_account { get; set; }
    }
}
