//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace The_Intellect_Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class Themes
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Id_section { get; set; }
        public int Id_user { get; set; }
    }
}
