//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace The_Intellect_Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class Words
    {
        public int Id { get; set; }
        public int Id_themes { get; set; }
        public string Word { get; set; }
        public string Question { get; set; }
        public string Answer { get; set; }
        public string Variation_2 { get; set; }
        public string Variation_3 { get; set; }
        public string Variation_4 { get; set; }
        public string Determination { get; set; }
    }
}
